---
version: "3.1"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - /home/ezarr/config/gluetun:/gluetun
      - /home/ezarr/tmp:/tmp
    environment:
      - "VPN_SERVICE_PROVIDER={provider}"
      - "VPN_TYPE={protocol}"
      - "SERVER_CITIES={cities_list}"
      - "OPENVPN_USER={user}"
      - "TZ={timezone}"
    ports:
      - 8989:8989 # sonarr
      - 7878:7878 # radarr
      - 5055:5055 # overseer
      - 9696:9696 # prowlarr
      - 8081:8080 # sabnzbd
      - 8181:8181 # tautulli
    restart: always

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ={timezone}
    volumes:
      - /home/ezarr/config/sonarr-config:/config
      - /home/ezarr/data:/data
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ={timezone}
    volumes:
      - /home/ezarr/config/radarr-config:/config
      - /home/ezarr/data:/data
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    network_mode: "service:gluetun"
    environment:
      - PUID=13009
      - PGID=13000
      - UMASK=002
      - TZ={timezone}
    volumes:
      - /home/ezarr/config/overseerr-config:/app/config
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=13006
      - PGID=13000
      - UMASK=002
      - TZ={timezone}
    volumes:
      - /home/ezarr/config/prowlarr-config:/config
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=13010
      - PGID=13000
      - VERSION=docker
      - PLEX_CLAIM=
    volumes:
      - /home/ezarr/config/plex-config:/config
      - /home/ezarr/data/media:/media
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    network_mode: "service:gluetun"
    depends_on:
      - plex
    environment:
      - PUID=${UID}
      - PGID=13000
      - TZ={timezone}
    volumes:
      - /home/ezarr/config/tautulli-config:/config
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: "service:gluetun"
    environment:
      - PUID=13011
      - PGID=13000
      - UMASK=002
      - TZ={timezone}
    volumes:
      - /home/ezarr/config/sabnzbd-config:/config
      - /home/ezarr/data/usenet:/data/usenet
    restart: unless-stopped
